on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: Is this a dry run -- i.e. do NOT actually  run the command
        required: false
        type: boolean
        default: false
      firstRelease:
        description: Is this the first release?
        required: false
        type: boolean
        default: false
jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      # Step 1: build the cargo container for everything
      - run: cargo build --release
      # Step 2: Upload
      - uses: actions/upload-artifact@v3
        name: Upload ${{ matrix.os }} artifacts
        with:
          name: ${{ matrix.os }}-build-artifact-${{ github.sha }}
          path: |
            target/release/*terminal*
            !target/release/*terminal*.d
  conglomerate:
    name: Combine things
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          path: target/
      - run: mkdir -p libraries && cp target/**/*terminal* ./libraries
      - name: Make full release artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}-libs
          path: libraries/
  version-bump:
    name: Version Bump
    runs-on: ubuntu-latest
    needs: conglomerate
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
      - run: deno install -A -n version-bump https://deno.land/x/version_bump/cli.ts
        name: Install Version bump
      - run: git config user.name "release bot" && git config user.email "jhechtf+release-bot@gmail.com"
        name: Configure release bot user in git
      - run: version-bump --firstRelease=${{ github.event.inputs.firstRelease }} --dryRun=${{ github.event.inputs.dryRun }}
        name: run verison bump tool
      - run: git push && git push --tags
        if: ${{ github.event.inputs.dryRun == 'false' }}
